USE [SGC]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CONSULTA]') AND type in (N'U'))
DROP TABLE [dbo].[CONSULTA]

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MEDICO]') AND type in (N'U'))
DROP TABLE [dbo].[MEDICO]

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PACIENTE]') AND type in (N'U'))
DROP TABLE [dbo].[PACIENTE]
GO
	
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PACIENTE](
	[PK_COD_PACIENTE] [int] IDENTITY(1,1) NOT NULL,
	[VC_NOME_PACIENTE] [varchar](100) NOT NULL,
	[TXT_HISTORICO_PACIENTE] [text] NOT NULL,
 CONSTRAINT [PK_PACIENTE] PRIMARY KEY CLUSTERED 
(
	[PK_COD_PACIENTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

CREATE TABLE [dbo].[MEDICO](
	[PK_COD_MEDICO] [int] IDENTITY(1,1) NOT NULL,
	[VC_NOME_MEDICO] [varchar](100) NULL,
	[VC_ESPECIALIDADE_MEDICO] [varchar](100) NULL,
 CONSTRAINT [PK_MEDICO] PRIMARY KEY CLUSTERED 
(
	[PK_COD_MEDICO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[CONSULTA](
	[PK_COD_CONSULTA] [int] IDENTITY(1,1) NOT NULL,
	[FK_COD_PACIENTE] [int] NOT NULL,
	[FK_COD_MEDICO] [int] NOT NULL,
	[TXT_RECEITA] [text] NULL,
	[VC_HORARIO] [varchar](100) NULL,
 CONSTRAINT [PK_CONSULTA] PRIMARY KEY CLUSTERED 
(
	[PK_COD_CONSULTA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[CONSULTA]  WITH CHECK ADD  CONSTRAINT [FK_CONSULTA_PACIENTE1] FOREIGN KEY([FK_COD_PACIENTE])
REFERENCES [dbo].[PACIENTE] ([PK_COD_PACIENTE])
GO

ALTER TABLE [dbo].[CONSULTA] CHECK CONSTRAINT [FK_CONSULTA_PACIENTE1]
GO
